import garden_mantis_i from "./garden_mantis.png";
export const garden_mantis = garden_mantis_i;
import vampire_crab_i from "./vampire_crab.png";
export const vampire_crab = vampire_crab_i;
import mutated_angler_i from "./mutated_angler.png";
export const mutated_angler = mutated_angler_i;
import void_ray_i from "./void_ray.png";
export const void_ray = void_ray_i;
import green_pearl_i from "./green_pearl.png";
export const green_pearl = green_pearl_i;
import stripeshell_snail_i from "./stripeshell_snail.png";
export const stripeshell_snail = stripeshell_snail_i;
import blue_marlin_i from "./blue_marlin.png";
export const blue_marlin = blue_marlin_i;
import sushi_i from "./sushi.png";
export const sushi = sushi_i;
import inky_dragonfly_i from "./inky_dragonfly.png";
export const inky_dragonfly = inky_dragonfly_i;
import trout_dinner_i from "./trout_dinner.png";
export const trout_dinner = trout_dinner_i;
import hydratepro_fertilizer_i from "./hydratepro_fertilizer.png";
export const hydratepro_fertilizer = hydratepro_fertilizer_i;
import giant_goldfish_i from "./giant_goldfish.png";
export const giant_goldfish = giant_goldfish_i;
import fisherman_s_brew_i from "./fisherman_s_brew.png";
export const fisherman_s_brew = fisherman_s_brew_i;
import enchanted_pupfish_i from "./enchanted_pupfish.png";
export const enchanted_pupfish = enchanted_pupfish_i;
import shimmerfin_i from "./shimmerfin.png";
export const shimmerfin = shimmerfin_i;
import long_nosed_unicorn_fish_i from "./long_nosed_unicorn_fish.png";
export const long_nosed_unicorn_fish = long_nosed_unicorn_fish_i;
